"""Domain models for Module 21 — Web Intelligence."""

import uuid
from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, Field, HttpUrl

from max.web_intelligence.domain.enums import (
    CitationStyle,
    ConflictType,
    ContentTrustLevel,
    EvidenceConfidence,
    EvidenceType,
    FreshnessPolicy,
    ResearchDepth,
    ResearchMode,
    ResearchPriority,
    ResearchStatus,
    SourceAuthority,
    SourceFreshness,
    SourceType,
)


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


class ResearchObjective(BaseModel):
    """Core research goal and focus question."""

    topic: str = Field(description="Primary topic or entity under investigation")
    question: str = Field(description="Core question to be answered by research")
    sub_questions: list[str] = Field(
        default_factory=list, description="Sub-questions to clarify objective"
    )


class ResearchScope(BaseModel):
    """Scope boundaries for research execution."""

    time_range_days: int | None = Field(
        default=None, description="Restrict search to recent N days if specified"
    )
    geographic_scope: str | None = Field(
        default=None, description="Geographic region focus (e.g., US, Global)"
    )
    language: str = Field(default="en", description="Target content language")
    allowed_domains: list[str] = Field(
        default_factory=list, description="Explicit whitelist of allowed domains"
    )
    blocked_domains: list[str] = Field(
        default_factory=list, description="Explicit blacklist of blocked domains"
    )
    required_source_types: list[SourceType] = Field(
        default_factory=list, description="Mandatory source types required"
    )
    excluded_source_types: list[SourceType] = Field(
        default_factory=list, description="Excluded source types"
    )


class ResearchConstraints(BaseModel):
    """Budget and operational resource limits."""

    max_queries: int = Field(default=5, ge=1, le=20, description="Maximum search queries to issue")
    max_sources: int = Field(
        default=10, ge=1, le=50, description="Maximum distinct sources to evaluate"
    )
    max_page_acquisitions: int = Field(
        default=10, ge=0, le=30, description="Maximum pages to fetch/acquire"
    )
    time_budget_seconds: float = Field(
        default=120.0, ge=5.0, le=600.0, description="Maximum research runtime timeout"
    )
    freshness_requirement: FreshnessPolicy = Field(
        default=FreshnessPolicy.NO_REQUIREMENT, description="Required freshness policy"
    )


class ResearchRequest(BaseModel):
    """High-level request initiating web research."""

    id: str = Field(default_factory=lambda: f"req_{uuid.uuid4().hex[:12]}")
    owner_id: str = Field(default="user_default", description="Requesting user/owner ID")
    objective: ResearchObjective = Field(description="Research goal and question")
    mode: ResearchMode = Field(
        default=ResearchMode.STANDARD_RESEARCH, description="Research mode"
    )
    depth: ResearchDepth = Field(default=ResearchDepth.STANDARD, description="Research depth tier")
    priority: ResearchPriority = Field(
        default=ResearchPriority.NORMAL, description="Execution priority"
    )
    scope: ResearchScope = Field(default_factory=ResearchScope, description="Scope boundaries")
    constraints: ResearchConstraints = Field(
        default_factory=ResearchConstraints, description="Operational constraints"
    )
    citation_style: CitationStyle = Field(
        default=CitationStyle.APA, description="Preferred citation formatting style"
    )
    created_at: datetime = Field(default_factory=_utc_now)


class ResearchPlanStep(BaseModel):
    """Individual step within a structured research plan."""

    step_number: int = Field(description="1-indexed step sequence")
    action_type: str = Field(
        description="Type of action (e.g. QUERY, ACQUIRE, EXTRACT, COMPARE, SYNTHESIZE)"
    )
    description: str = Field(description="Human-readable description of planned step")
    completed: bool = Field(default=False, description="Completion flag")


class ResearchPlan(BaseModel):
    """Structured plan generated by ResearchPlanner."""

    research_id: str = Field(description="Associated research request ID")
    steps: list[ResearchPlanStep] = Field(default_factory=list, description="Sequence of plan steps")
    planned_queries: list[str] = Field(
        default_factory=list, description="Initial list of planned search query strings"
    )
    created_at: datetime = Field(default_factory=_utc_now)


class ResearchQuery(BaseModel):
    """Individual search query generated by QueryPlanner."""

    id: str = Field(default_factory=lambda: f"qry_{uuid.uuid4().hex[:10]}")
    research_id: str = Field(description="Associated research request ID")
    original_query: str = Field(description="Raw generated query string")
    normalized_query: str = Field(description="Cleaned, normalized query string")
    purpose: str = Field(
        default="GENERAL", description="Purpose (PRIMARY, TECHNICAL, OFFICIAL, RECENT, ALTERNATIVE)"
    )
    issued_at: datetime = Field(default_factory=_utc_now)


class SearchResult(BaseModel):
    """Single result record returned from search provider."""

    id: str = Field(default_factory=lambda: f"res_{uuid.uuid4().hex[:10]}")
    query_id: str = Field(description="ID of query that yielded result")
    title: str = Field(description="Result page title")
    url: str = Field(description="Result URL")
    domain: str = Field(description="Domain host name")
    snippet: str = Field(description="Search snippet preview text")
    published_at: str | None = Field(default=None, description="Optional publication date string")
    retrieved_at: datetime = Field(default_factory=_utc_now)
    provider_name: str = Field(default="mock", description="Search provider name")
    rank: int = Field(default=1, ge=1, description="Search engine rank position")


class SearchRequest(BaseModel):
    """Request payload sent to SearchProvider."""

    query: str = Field(description="Search query string")
    max_results: int = Field(default=10, ge=1, le=50, description="Max results requested")
    freshness_filter: str | None = Field(default=None, description="Optional time filter")
    allowed_domains: list[str] = Field(default_factory=list)
    blocked_domains: list[str] = Field(default_factory=list)


class SearchResponse(BaseModel):
    """Container returned by SearchProvider.search()."""

    query: str
    provider_name: str
    results: list[SearchResult] = Field(default_factory=list)
    total_count: int = Field(default=0)
    executed_at: datetime = Field(default_factory=_utc_now)


class SourceMetadata(BaseModel):
    """Detailed metadata describing a web source."""

    url: str
    domain: str
    title: str = Field(default="Unknown Title")
    author: str | None = Field(default=None)
    publisher: str | None = Field(default=None)
    published_date: str | None = Field(default=None)
    modified_date: str | None = Field(default=None)
    retrieval_timestamp: datetime = Field(default_factory=_utc_now)
    language: str = Field(default="en")
    source_type: SourceType = Field(default=SourceType.UNKNOWN)
    canonical_url: str | None = Field(default=None)
    content_type: str = Field(default="text/html")
    http_status: int = Field(default=200)
    discovery_query: str | None = Field(default=None)


class SourceTrustMetadata(BaseModel):
    """Structured authority and reliability signals."""

    is_official: bool = Field(default=False)
    is_primary: bool = Field(default=False)
    has_known_author: bool = Field(default=False)
    has_publication_date: bool = Field(default=False)
    citations_present: bool = Field(default=False)
    domain_reputation_notes: str | None = Field(default=None)


class Source(BaseModel):
    """Discovered candidate web source."""

    id: str = Field(default_factory=lambda: f"src_{uuid.uuid4().hex[:10]}")
    research_id: str
    metadata: SourceMetadata
    authority: SourceAuthority = Field(default=SourceAuthority.UNKNOWN)
    freshness: SourceFreshness = Field(default=SourceFreshness.UNKNOWN)
    trust: SourceTrustMetadata = Field(default_factory=SourceTrustMetadata)
    is_acquired: bool = Field(default=False)
    is_duplicate: bool = Field(default=False)
    duplicate_of_id: str | None = Field(default=None)


class ContentSection(BaseModel):
    """Individual structural section of extracted web text."""

    heading: str | None = Field(default=None)
    text: str
    section_index: int = Field(default=0)


class WebContent(BaseModel):
    """Cleaned, extracted text content from a web document."""

    raw_text: str = Field(description="Full extracted visible text")
    sections: list[ContentSection] = Field(default_factory=list)
    links: list[dict[str, str]] = Field(default_factory=list, description="Extracted links metadata")
    headings: list[str] = Field(default_factory=list)
    word_count: int = Field(default=0)
    trust_level: ContentTrustLevel = Field(default=ContentTrustLevel.UNTRUSTED_WEB_CONTENT)


class WebDocument(BaseModel):
    """Acquired web document record."""

    id: str = Field(default_factory=lambda: f"doc_{uuid.uuid4().hex[:10]}")
    source_id: str
    url: str
    title: str
    content: WebContent
    acquired_at: datetime = Field(default_factory=_utc_now)
    content_hash: str = Field(default="")


class EvidenceQuoteReference(BaseModel):
    """Exact quote reference from document."""

    exact_quote: str
    section_index: int = Field(default=0)
    char_offset: int = Field(default=0)


class Evidence(BaseModel):
    """Single evidence claim connected to source provenance."""

    id: str = Field(default_factory=lambda: f"ev_{uuid.uuid4().hex[:10]}")
    research_id: str
    source_id: str
    document_id: str
    claim: str = Field(description="Extracted factual claim")
    evidence_type: EvidenceType = Field(default=EvidenceType.DIRECT_FACT)
    quote_ref: EvidenceQuoteReference | None = Field(default=None)
    confidence: EvidenceConfidence = Field(default=EvidenceConfidence.MEDIUM)
    source_url: str
    source_title: str
    published_date: str | None = Field(default=None)
    extracted_at: datetime = Field(default_factory=_utc_now)


class EvidenceConflict(BaseModel):
    """Structured representation of contradictory evidence between sources."""

    id: str = Field(default_factory=lambda: f"cnf_{uuid.uuid4().hex[:10]}")
    research_id: str
    conflict_type: ConflictType = Field(default=ConflictType.CLAIM_CONTRADICTION)
    claim_summary: str = Field(description="Topic or claim where conflict occurs")
    evidence_a: Evidence = Field(description="First conflicting evidence item")
    evidence_b: Evidence = Field(description="Second conflicting evidence item")
    notes: str = Field(default="Sources present conflicting information.")


class Citation(BaseModel):
    """First-class citation referencing a retrieved source."""

    id: str = Field(default_factory=lambda: f"cit_{uuid.uuid4().hex[:10]}")
    research_id: str
    source_id: str
    url: str
    title: str
    publisher: str | None = Field(default=None)
    author: str | None = Field(default=None)
    published_date: str | None = Field(default=None)
    retrieved_at: datetime = Field(default_factory=_utc_now)
    formatted_text: str = Field(description="Rendered citation string (e.g. APA format)")
    style: CitationStyle = Field(default=CitationStyle.APA)
    is_validated: bool = Field(default=True)


class ResearchFinding(BaseModel):
    """Synthesized key finding from evidence."""

    id: str = Field(default_factory=lambda: f"fnd_{uuid.uuid4().hex[:10]}")
    statement: str = Field(description="Key finding statement")
    supporting_evidence_ids: list[str] = Field(default_factory=list)
    citation_ids: list[str] = Field(default_factory=list)
    confidence: EvidenceConfidence = Field(default=EvidenceConfidence.MEDIUM)


class ResearchSummary(BaseModel):
    """High-level summary of research output."""

    overview: str = Field(description="Main summary overview text")
    key_points: list[str] = Field(default_factory=list)
    limitations: list[str] = Field(default_factory=list)
    uncertainties: list[str] = Field(default_factory=list)


class ResearchQualityReport(BaseModel):
    """Quality metrics evaluating research output."""

    objective_answered: bool = Field(default=True)
    sources_count: int = Field(default=0)
    distinct_domains_count: int = Field(default=0)
    conflicts_count: int = Field(default=0)
    citations_count: int = Field(default=0)
    freshness_satisfied: bool = Field(default=True)
    quality_score: float = Field(default=1.0, ge=0.0, le=1.0)
    notes: list[str] = Field(default_factory=list)


class ResearchSynthesis(BaseModel):
    """Final synthesized research document."""

    summary: ResearchSummary
    findings: list[ResearchFinding] = Field(default_factory=list)
    citations: list[Citation] = Field(default_factory=list)
    conflicts: list[EvidenceConflict] = Field(default_factory=list)
    quality_report: ResearchQualityReport = Field(default_factory=ResearchQualityReport)


class ResearchResult(BaseModel):
    """Complete research result object."""

    research_id: str
    objective: ResearchObjective
    status: ResearchStatus
    mode: ResearchMode
    depth: ResearchDepth
    synthesis: ResearchSynthesis
    sources: list[Source] = Field(default_factory=list)
    evidence: list[Evidence] = Field(default_factory=list)
    queries_used: list[ResearchQuery] = Field(default_factory=list)
    created_at: datetime
    completed_at: datetime = Field(default_factory=_utc_now)
    total_duration_seconds: float = Field(default=0.0)


class ResearchAuditEvent(BaseModel):
    """Structured audit trail record for research events."""

    id: str = Field(default_factory=lambda: f"aud_{uuid.uuid4().hex[:10]}")
    timestamp: datetime = Field(default_factory=_utc_now)
    research_id: str
    event_type: str
    owner_id: str = Field(default="system")
    details: dict[str, Any] = Field(default_factory=dict)
