"""Computer control API schemas package."""

from max.computer.schemas.requests import (
    ActionExecutionRequestSchema,
    KeyboardPressRequestSchema,
    KeyboardShortcutRequestSchema,
    KeyboardTypeRequestSchema,
    MouseClickRequestSchema,
    MouseDragRequestSchema,
    MouseMoveRequestSchema,
    MouseScrollRequestSchema,
    ScreenCaptureRequestSchema,
    SequenceExecutionRequestSchema,
    WindowMoveRequestSchema,
    WindowResizeRequestSchema,
)
from max.computer.schemas.responses import (
    ActionSequenceResponse,
    ComputerActionFailureResponse,
    ComputerActionResponse,
    ComputerActionResultResponse,
    ComputerStateResponse,
    ComputerStatusResponse,
    CursorPositionResponse,
    DisplayResponse,
    ScreenCaptureResponse,
    WindowListResponse,
    WindowResponse,
)

__all__ = [
    "ScreenCaptureRequestSchema",
    "MouseMoveRequestSchema",
    "MouseClickRequestSchema",
    "MouseDragRequestSchema",
    "MouseScrollRequestSchema",
    "KeyboardPressRequestSchema",
    "KeyboardTypeRequestSchema",
    "KeyboardShortcutRequestSchema",
    "WindowMoveRequestSchema",
    "WindowResizeRequestSchema",
    "ActionExecutionRequestSchema",
    "SequenceExecutionRequestSchema",
    "ComputerStatusResponse",
    "DisplayResponse",
    "CursorPositionResponse",
    "ScreenCaptureResponse",
    "WindowResponse",
    "WindowListResponse",
    "ComputerStateResponse",
    "ComputerActionResultResponse",
    "ComputerActionFailureResponse",
    "ComputerActionResponse",
    "ActionSequenceResponse",
]
