"""Domain models for Module 30 — Proactive Intelligence Engine."""

from datetime import UTC, datetime
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field

from max.proactive.domain.enums import (
    ActionStatus,
    ActionType,
    AttentionCost,
    AutonomyLevel,
    DecisionType,
    FeedbackType,
    ImportanceLevel,
    RulePriority,
    RuleStatus,
    SignalSource,
    UrgencyLevel,
    UserState,
)


def _utc_now() -> datetime:
    return datetime.now(UTC)


def _uuid_str() -> str:
    return str(uuid4())


class ProactiveSignal(BaseModel):
    """Normalized incoming signal observed by Proactive Engine."""

    signal_id: str = Field(default_factory=_uuid_str)
    source: SignalSource
    signal_type: str = Field(description="Extensible event type key, e.g., calendar.deadline_approaching")
    occurred_at: datetime = Field(default_factory=_utc_now)
    received_at: datetime = Field(default_factory=_utc_now)
    payload_reference: dict[str, Any] = Field(
        default_factory=dict,
        description="References/metadata for untrusted signal payload data",
    )
    importance_hint: ImportanceLevel = Field(default=ImportanceLevel.MEDIUM)
    owner_id: str = Field(default="default_owner")
    deduplication_key: str | None = Field(
        default=None, description="Deterministic deduplication key if provided"
    )
    metadata: dict[str, Any] = Field(default_factory=dict)


class ProactiveCandidate(BaseModel):
    """Evaluated potential proactive opportunity derived from signals."""

    candidate_id: str = Field(default_factory=_uuid_str)
    owner_id: str = Field(default="default_owner")
    signal_id: str
    candidate_type: str
    description: str
    importance: ImportanceLevel = Field(default=ImportanceLevel.MEDIUM)
    urgency: UrgencyLevel = Field(default=UrgencyLevel.MEDIUM)
    confidence: float = Field(default=0.7, ge=0.0, le=1.0)
    relevance: float = Field(default=0.7, ge=0.0, le=1.0)
    novelty: float = Field(default=1.0, ge=0.0, le=1.0)
    actionability: bool = Field(default=True)
    sensitivity: str = Field(default="LOW", description="LOW, MEDIUM, HIGH, SENSITIVE")
    attention_cost: AttentionCost = Field(default=AttentionCost.LOW)
    category: str = Field(default="GENERAL")
    created_at: datetime = Field(default_factory=_utc_now)
    expires_at: datetime | None = Field(default=None)
    deduplication_key: str | None = Field(default=None)
    metadata: dict[str, Any] = Field(default_factory=dict)


class ProactiveDecision(BaseModel):
    """Policy-aware decision explaining whether to stay silent or act."""

    decision_id: str = Field(default_factory=_uuid_str)
    candidate_id: str
    owner_id: str = Field(default="default_owner")
    decision_type: DecisionType
    reason: str = Field(description="Structured concise non-private decision rationale")
    confidence: float = Field(default=0.7, ge=0.0, le=1.0)
    policy_version: str = Field(default="1.0.0")
    proposed_action: dict[str, Any] | None = Field(default=None)
    autonomy_level: AutonomyLevel = Field(default=AutonomyLevel.LEVEL_1)
    created_at: datetime = Field(default_factory=_utc_now)
    expires_at: datetime | None = Field(default=None)
    metadata: dict[str, Any] = Field(default_factory=dict)


class ProactiveAction(BaseModel):
    """Represented action generated by a proactive decision."""

    action_id: str = Field(default_factory=_uuid_str)
    decision_id: str
    owner_id: str = Field(default="default_owner")
    action_type: ActionType
    target: str = Field(default="SYSTEM", description="Target component or system")
    arguments: dict[str, Any] = Field(default_factory=dict)
    risk_level: str = Field(default="LOW", description="LOW, MEDIUM, HIGH, CRITICAL")
    permission_requirement: str | None = Field(default=None)
    status: ActionStatus = Field(default=ActionStatus.PENDING)
    created_at: datetime = Field(default_factory=_utc_now)
    metadata: dict[str, Any] = Field(default_factory=dict)


class ProactiveOutcome(BaseModel):
    """Execution outcome tracking proactive action completion."""

    outcome_id: str = Field(default_factory=_uuid_str)
    action_id: str
    owner_id: str = Field(default="default_owner")
    status: ActionStatus
    user_response: str | None = Field(default=None)
    result: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=_utc_now)
    metadata: dict[str, Any] = Field(default_factory=dict)


class ProactiveFeedback(BaseModel):
    """Structured user feedback on proactive interventions."""

    feedback_id: str = Field(default_factory=_uuid_str)
    decision_id: str
    owner_id: str = Field(default="default_owner")
    feedback_type: FeedbackType
    value: str | float | int | bool = Field(default=True)
    source: str = Field(default="USER_EXPLICIT")
    created_at: datetime = Field(default_factory=_utc_now)
    metadata: dict[str, Any] = Field(default_factory=dict)


class ProactiveRule(BaseModel):
    """Structured rule definition evaluated deterministically without code execution."""

    rule_id: str = Field(default_factory=_uuid_str)
    owner_id: str = Field(default="default_owner")
    name: str
    description: str
    source: SignalSource | None = Field(default=None)
    candidate_type: str | None = Field(default=None)
    min_importance: ImportanceLevel = Field(default=ImportanceLevel.LOW)
    min_urgency: UrgencyLevel = Field(default=UrgencyLevel.LOW)
    min_confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    min_relevance: float = Field(default=0.5, ge=0.0, le=1.0)
    allowed_user_states: list[UserState] = Field(
        default_factory=lambda: [UserState.AVAILABLE, UserState.FOCUSED]
    )
    decision_type: DecisionType = Field(default=DecisionType.NOTIFY)
    priority: RulePriority = Field(default=RulePriority.DEFAULT)
    version: str = Field(default="1.0.0")
    status: RuleStatus = Field(default=RuleStatus.ACTIVE)
    cooldown_seconds: float = Field(default=14400.0)
    created_at: datetime = Field(default_factory=_utc_now)
    updated_at: datetime = Field(default_factory=_utc_now)
    effective_from: datetime | None = Field(default=None)
    effective_until: datetime | None = Field(default=None)
    metadata: dict[str, Any] = Field(default_factory=dict)


class AttentionBudget(BaseModel):
    """User attention budget state tracking notification rates."""

    user_id: str = Field(default="default_owner")
    hourly_count: int = Field(default=0)
    daily_count: int = Field(default=0)
    last_reset_hour: int = Field(default=0)
    last_reset_day: int = Field(default=0)
    max_per_hour: int = Field(default=5)
    max_per_day: int = Field(default=20)


class ProactiveDigest(BaseModel):
    """Grouped non-urgent notification digest."""

    digest_id: str = Field(default_factory=_uuid_str)
    owner_id: str = Field(default="default_owner")
    candidate_ids: list[str] = Field(default_factory=list)
    summary: str
    created_at: datetime = Field(default_factory=_utc_now)


class ProactiveSimulationResult(BaseModel):
    """Output summary of proactive simulation or dry run."""

    signal: ProactiveSignal
    candidates: list[ProactiveCandidate]
    decision: ProactiveDecision
    proposed_action: ProactiveAction | None = Field(default=None)
