"""Domain package exports for Module 17 — Filesystem Agent."""

from max.filesystem.domain.action import (
    FileOperation,
    FileOperationFailure,
    FileOperationRequest,
    FileOperationResult,
)
from max.filesystem.domain.enums import (
    FileEncoding,
    FileFailureReason,
    FileOperationStatus,
    FileOperationType,
    FilesystemCapability,
    FileType,
)
from max.filesystem.domain.exceptions import (
    FileAlreadyExistsError,
    FilesystemBackendUnavailableError,
    FilesystemError,
    FilesystemNotFoundError,
    FilesystemPermissionError,
    FilesystemTimeoutError,
    FileTooLargeError,
    InvalidFilesystemOperationError,
    PathTraversalError,
    PathValidationError,
    ProtectedPathError,
    SandboxViolationError,
    SearchLimitError,
    SymlinkEscapeError,
)
from max.filesystem.domain.models import (
    CompareResult,
    DirectoryListing,
    DirectoryMetadata,
    FileMetadata,
    FileReadResult,
    FileSystemEntry,
    FilesystemTraceEvent,
    FileWriteResult,
    HashResult,
    PathReference,
    SearchFilter,
    SearchResponseData,
    SearchResultEntry,
)

__all__ = [
    # Enums
    "FileType",
    "FileOperationType",
    "FileOperationStatus",
    "FileFailureReason",
    "FilesystemCapability",
    "FileEncoding",
    # Domain Models
    "PathReference",
    "FileMetadata",
    "DirectoryMetadata",
    "FileSystemEntry",
    "DirectoryListing",
    "FileReadResult",
    "FileWriteResult",
    "SearchFilter",
    "SearchResultEntry",
    "SearchResponseData",
    "HashResult",
    "CompareResult",
    "FilesystemTraceEvent",
    "FileOperationRequest",
    "FileOperationResult",
    "FileOperationFailure",
    "FileOperation",
    # Exceptions
    "FilesystemError",
    "PathValidationError",
    "PathTraversalError",
    "ProtectedPathError",
    "SandboxViolationError",
    "SymlinkEscapeError",
    "FilesystemNotFoundError",
    "FileAlreadyExistsError",
    "FilesystemPermissionError",
    "FileTooLargeError",
    "SearchLimitError",
    "FilesystemTimeoutError",
    "FilesystemBackendUnavailableError",
    "InvalidFilesystemOperationError",
]
