"""Domain package for Module 31 — Learning & Personalization Engine."""

from max.personalization.domain.enums import (
    HypothesisStatus,
    LearningMode,
    LearningSignalSource,
    PersonalizationEventType,
    PreferenceCategory,
    PreferenceScope,
    PreferenceSource,
    PreferenceStatus,
)
from max.personalization.domain.exceptions import (
    HypothesisNotFoundError,
    InvalidPreferenceError,
    PermissionEscalationViolationError,
    PersonalizationError,
    PreferenceConflictError,
    PreferenceNotFoundError,
    SensitiveInferenceViolationError,
)
from max.personalization.domain.models import (
    AutonomyProfile,
    CommunicationProfile,
    LearningObservation,
    LearningSignal,
    NotificationProfile,
    PersonalizationFeedback,
    PersonalizationHistoryEntry,
    PersonalizationProfile,
    PersonalizationSettingsState,
    PersonalizationSimulationResult,
    Preference,
    PreferenceEvidence,
    PreferenceHypothesis,
    ProactivityProfile,
    ResolvedPreference,
    WorkflowProfile,
)

__all__ = [
    "PreferenceSource",
    "PreferenceStatus",
    "PreferenceScope",
    "PreferenceCategory",
    "HypothesisStatus",
    "LearningMode",
    "LearningSignalSource",
    "PersonalizationEventType",
    "PersonalizationError",
    "PreferenceNotFoundError",
    "HypothesisNotFoundError",
    "InvalidPreferenceError",
    "SensitiveInferenceViolationError",
    "PermissionEscalationViolationError",
    "PreferenceConflictError",
    "Preference",
    "PreferenceEvidence",
    "LearningSignal",
    "LearningObservation",
    "PreferenceHypothesis",
    "CommunicationProfile",
    "NotificationProfile",
    "ProactivityProfile",
    "AutonomyProfile",
    "WorkflowProfile",
    "PersonalizationProfile",
    "ResolvedPreference",
    "PersonalizationFeedback",
    "PersonalizationHistoryEntry",
    "PersonalizationSimulationResult",
    "PersonalizationSettingsState",
]
