from enum import StrEnum


class PreferenceSource(StrEnum):
    """Source of a preference or evidence."""

    EXPLICIT_USER = "EXPLICIT_USER"
    USER_CORRECTION = "USER_CORRECTION"
    USER_FEEDBACK = "USER_FEEDBACK"
    OBSERVED_BEHAVIOR = "OBSERVED_BEHAVIOR"
    CONVERSATION = "CONVERSATION"
    PROACTIVE_FEEDBACK = "PROACTIVE_FEEDBACK"
    TASK_HISTORY = "TASK_HISTORY"
    NOTIFICATION_HISTORY = "NOTIFICATION_HISTORY"
    AUTOMATION_HISTORY = "AUTOMATION_HISTORY"
    SYSTEM_DEFAULT = "SYSTEM_DEFAULT"


class PreferenceStatus(StrEnum):
    """Lifecycle status of a preference."""

    ACTIVE = "ACTIVE"
    PENDING = "PENDING"
    DISPUTED = "DISPUTED"
    DISABLED = "DISABLED"
    EXPIRED = "EXPIRED"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"


class PreferenceScope(StrEnum):
    """Applicability scope of a preference."""

    GLOBAL = "GLOBAL"
    CONVERSATION = "CONVERSATION"
    PROJECT = "PROJECT"
    TASK = "TASK"
    TIME_WINDOW = "TIME_WINDOW"
    APPLICATION = "APPLICATION"
    INTEGRATION = "INTEGRATION"
    CATEGORY = "CATEGORY"


class PreferenceCategory(StrEnum):
    """Extensible domain categories for user preferences."""

    COMMUNICATION = "COMMUNICATION"
    NOTIFICATION = "NOTIFICATION"
    PROACTIVITY = "PROACTIVITY"
    AUTONOMY = "AUTONOMY"
    WORKFLOW = "WORKFLOW"
    TOOLS = "TOOLS"
    SCHEDULING = "SCHEDULING"
    VOICE = "VOICE"
    LANGUAGE = "LANGUAGE"
    RESPONSE_FORMAT = "RESPONSE_FORMAT"
    TECHNICAL_DETAIL = "TECHNICAL_DETAIL"
    PRIVACY = "PRIVACY"
    UI = "UI"
    CODING = "CODING"
    DOCUMENTS = "DOCUMENTS"
    RESEARCH = "RESEARCH"


class HypothesisStatus(StrEnum):
    """Status of an inferred preference hypothesis."""

    NEW = "NEW"
    STRENGTHENING = "STRENGTHENING"
    STABLE = "STABLE"
    CONFLICTED = "CONFLICTED"
    WEAKENING = "WEAKENING"
    REJECTED = "REJECTED"
    PROMOTED = "PROMOTED"


class LearningMode(StrEnum):
    """Operating mode for automated behavioral learning."""

    OFF = "OFF"
    EXPLICIT_ONLY = "EXPLICIT_ONLY"
    ASSISTED = "ASSISTED"
    ADAPTIVE = "ADAPTIVE"


class LearningSignalSource(StrEnum):
    """Origin module or trigger for incoming learning signals."""

    CONVERSATION = "CONVERSATION"
    MEMORY = "MEMORY"
    TASK = "TASK"
    NOTIFICATION = "NOTIFICATION"
    PROACTIVE = "PROACTIVE"
    AUTOMATION = "AUTOMATION"
    INTEGRATION = "INTEGRATION"
    USER_FEEDBACK = "USER_FEEDBACK"
    TOOL_USAGE = "TOOL_USAGE"
    SCHEDULE = "SCHEDULE"
    APPLICATION = "APPLICATION"
    SYSTEM = "SYSTEM"


class PersonalizationEventType(StrEnum):
    """Audit event types for personalization lifecycle actions."""

    PREFERENCE_CREATED = "PREFERENCE_CREATED"
    PREFERENCE_UPDATED = "PREFERENCE_UPDATED"
    PREFERENCE_CONFIRMED = "PREFERENCE_CONFIRMED"
    PREFERENCE_REJECTED = "PREFERENCE_REJECTED"
    PREFERENCE_CORRECTED = "PREFERENCE_CORRECTED"
    PREFERENCE_EXPIRED = "PREFERENCE_EXPIRED"
    HYPOTHESIS_CREATED = "HYPOTHESIS_CREATED"
    HYPOTHESIS_PROMOTED = "HYPOTHESIS_PROMOTED"
    HYPOTHESIS_REJECTED = "HYPOTHESIS_REJECTED"
    LEARNING_PAUSED = "LEARNING_PAUSED"
    LEARNING_RESUMED = "LEARNING_RESUMED"
    PERSONALIZATION_RESET = "PERSONALIZATION_RESET"
    CATEGORY_RESET = "CATEGORY_RESET"
