"""Module 15 — Permission & Security layer for MAX Personal AI system."""

from max.security.container import (
    SecurityContainer,
    get_security_container,
    reset_security_container,
)
from max.security.domain import (
    ApprovalDecision,
    ApprovalRequest,
    ApprovalStatus,
    ApprovalType,
    AuthorizedExecutionRequest,
    DecisionReason,
    EmergencyBlock,
    Permission,
    PermissionAction,
    PermissionCondition,
    PermissionDecision,
    PermissionDecisionStatus,
    PermissionEffect,
    PermissionGrant,
    PermissionGrantType,
    PermissionPolicy,
    PermissionRequest,
    PermissionResource,
    PermissionRule,
    PermissionScope,
    PermissionSubject,
    PermissionSubjectType,
    ResourceSensitivity,
    RiskLevel,
    SecurityContext,
    SecurityEvent,
    SecurityEventType,
    SecurityMode,
    SecurityModeState,
    SecurityPrincipal,
    SecurityViolation,
    SecurityViolationType,
)
from max.security.services import (
    ApprovalService,
    KillSwitchService,
    PermissionEvaluator,
    PermissionGate,
    PermissionGrantService,
    PolicyService,
    SecurityAuditService,
    SecurityContextBuilder,
    SecurityModeService,
    SecurityViolationService,
)

__all__ = [
    # Domain
    "PermissionSubject",
    "PermissionSubjectType",
    "SecurityPrincipal",
    "PermissionResource",
    "ResourceSensitivity",
    "PermissionAction",
    "PermissionScope",
    "PermissionEffect",
    "RiskLevel",
    "PermissionCondition",
    "PermissionRule",
    "PermissionPolicy",
    "Permission",
    "SecurityContext",
    "PermissionRequest",
    "PermissionDecision",
    "PermissionDecisionStatus",
    "DecisionReason",
    "ApprovalRequest",
    "ApprovalDecision",
    "ApprovalStatus",
    "ApprovalType",
    "PermissionGrant",
    "PermissionGrantType",
    "EmergencyBlock",
    "SecurityModeState",
    "SecurityMode",
    "SecurityEvent",
    "SecurityEventType",
    "SecurityViolation",
    "SecurityViolationType",
    "AuthorizedExecutionRequest",
    # Services
    "SecurityContextBuilder",
    "PermissionEvaluator",
    "PermissionGate",
    "PolicyService",
    "PermissionGrantService",
    "ApprovalService",
    "SecurityModeService",
    "KillSwitchService",
    "SecurityAuditService",
    "SecurityViolationService",
    # Container
    "SecurityContainer",
    "get_security_container",
    "reset_security_container",
]
